apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gestion-coiffure-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gestion-coiffure.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gestion-coiffure-service
            port:
              number: 80